# Generated by Django 4.1.4 on 2022-12-28 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0002_services_remove_pagos_usuario_paymentuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
