# Generated by Django 4.1.4 on 2022-12-29 00:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0003_alter_pagos_fecha_pago'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pagos',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='paymentuser',
            name='services_id',
        ),
        migrations.AddField(
            model_name='pagos',
            name='services_id',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='pagos.services'),
            preserve_default=False,
        ),
    ]
