# Generated by Django 4.1.4 on 2022-12-29 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0004_remove_pagos_servicio_remove_paymentuser_services_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentuser',
            name='services_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='service', to='pagos.services'),
            preserve_default=False,
        ),
    ]
